// TBLAccesoCuadrillas
let
    Source = Excel.CurrentWorkbook(){[Name="AccesoCuadrillas"]}[Content],
    ChangedType = Table.TransformColumnTypes(Source,{{"Compania", type text}, {"Departamento", type text}, {"CCTec", type text}, {"Acceso", type text}, {"Cargo", type text}, {"A単o", Int64.Type}, {"Mes", Int64.Type}, {"FechaMin", type date}, {"FechaMax", type date}}),
    MergedMesAct = Table.NestedJoin(ChangedType, {"A単o", "Mes"}, MesAct, {"A単o", "Mes"}, "MesAct", JoinKind.LeftAnti),
    RemovedOtherColumns = Table.SelectColumns(MergedMesAct,{"Compania", "Departamento", "CCTec", "Acceso", "Cargo", "A単o", "Mes", "FechaMin", "FechaMax"})
in
    RemovedOtherColumns